
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - PHP_IDE_CONFIG=serverName=rtandrew
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "
        php-fpm &
        /usr/local/bin/auto-reload.sh &
        wait
      "

  nginx:
    volumes:
      - ./:/var/www/html
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

  node:
    command: sh -c "npm install && npm run watch"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules

  # Add a file watcher service for auto-reload
  watcher:
    image: alpine:latest
    container_name: rtandrew-watcher
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
        apk add --no-cache inotify-tools docker-cli &&
        while inotifywait -e modify,create,delete -r /var/www/html/app /var/www/html/config /var/www/html/routes /var/www/html/resources/views;
        do
          echo 'Files changed, clearing Laravel caches...' &&
          docker exec rtandrew-app php artisan config:clear &&
          docker exec rtandrew-app php artisan cache:clear &&
          docker exec rtandrew-app php artisan view:clear &&
          docker exec rtandrew-app php artisan route:clear
        done
      "
    networks:
      - rtandrew-network
    depends_on:
      - app
