[phases.setup]
nixPkgs = ['...', 'composer','npm']

[phases.build]
cmds = ['composer install', 'php artisan config:cache', 'php artisan route:cache', 'php artisan migrate --force']

[start]
cmd = 'php artisan serve'