[phases.setup]
nixPkgs = ['...', 'python']

[phases.install]
cmds = ['mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx', 'composer install --ignore-platform-reqs', 'npm i']

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache', 'php artisan migrate --force', 'npm run prod']